### ISSUE TITLE
Keybord hidden on Global show

### ISSUE THREAD

**Issue by AndroFlo** [lamydev/Android-Notification#6]
When a global notification is displayed, if the keyboard is visible it his hidden since notification is visible.
How change this ?

Thank's

**Comment by manusanilea** [comment]
Hello,
The problem can be solved by changing the flags of the LayoutParams when adding the view with the WidownManager.

In fact, the flag `FLAG_NOT_TOUCH_MODAL `must be used with the flag `FLAG_NOT_FOCUSABLE` :
![android-notification-change-01](https://user-images.githubusercontent.com/17569697/35097893-66128826-fc52-11e7-9d4a-96410f37f3be.png)

**Comment by manusanilea** [comment]
Furthermore, if we want to display the notification correctly, we need to use tow more flags :
- `FLAG_LAYOUT_IN_SCREEN`
- `FLAG_LAYOUT_INSET_DECOR`.

The result is :
![android-notification-change-02](https://user-images.githubusercontent.com/17569697/35098239-aae9dac0-fc53-11e7-98a1-31774a423ffc.png)
